---
data-infrastructure:
  channel: '#data-infrastructure'
  exclude_labels:
    - WIP
    - ignore
  exclude_titles:
    - DO NOT MERGE
    - PROTOTYPE
    - WIP
  use_labels: true

data-insights:
  channel: '#data-insights'
  exclude_labels:
    - WIP
    - ignore
  exclude_titles:
    - DO NOT MERGE
    - PROTOTYPE
    - WIP
  use_labels: true

data-products:
  channel: '#data-products'
  exclude_labels:
    - WIP
    - ignore
  exclude_titles:
    - DO NOT MERGE
    - PROTOTYPE
    - WIP
  repos:
    - data-community-tech-docs
    - differential-privacy-tests
    - govuk-accessibility-reports
    - govuk-content-metadata
    - govuk-content-similarity
    - govuk-data-science-workshop
    - govuk-datalabs-streamlit-NER
    - govuk-entity-personalisation
    - govuk-feedback-pipeline
    - govuk-feedback-spam-classifier
    - govuk-intent-detector
    - govuk-knowledge-graph
    - govuk-mongodb-content
    - govuk-network-data
    - govuk-networks
    - govuk-networkx-tutorial
    - govuk-related-links-recommender
    - govuk-spaCy
    - govuk-user-feedback-processing
    - govuk-user-journey-analysis-tools
    - govuk-user-journey-models
    - govuk-wuj-network-analysis
    - govuk_ab_analysis
    - insights-data-visualisation-templates
    - lstm_segmentation
    - related-links-data
    - tagging-suggester
  use_labels: true

fun-workstream-gds-community:
  channel: '#gds-community'
  quotes:
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> feel the way you feel
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> talk about how you're feeling
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> ask for feedback
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> have days off
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> have off days
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> go outside during work
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> switch off at the end of the day
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> not constantly check chat and emails
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> have screen breaks
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> say you're not comfortable with something
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> raise your concerns
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> be you
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> change your mind
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> say no
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> have other things going on
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> forget things
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> have a meeting
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> not have a meeting
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> turn off notifications
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> block time out to think and reflect
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> approach tasks your own way
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> work flexibly
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> turn your camera off
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> take time off if you're not well
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> make mistakes
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> say you don't understand
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> ask for help
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> put yourself first
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> love what you do

fun-workstream-govuk:
  channel: '#govuk'
  quotes:
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> feel the way you feel
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> talk about how you're feeling
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> ask for feedback
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> have days off
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> have off days
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> go outside during work
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> switch off at the end of the day
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> not constantly check chat and emails
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> have screen breaks
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> say you're not comfortable with something
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> raise your concerns
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> be you
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> change your mind
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> say no
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> have other things going on
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> forget things
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> have a meeting
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> not have a meeting
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> turn off notifications
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> block time out to think and reflect
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> approach tasks your own way
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> work flexibly
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> turn your camera off
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> take time off if you're not well
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> make mistakes
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> say you don't understand
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> ask for help
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> put yourself first
    - <https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/this-is-gds/its-ok-to|It's ok to> love what you do

govuk-accounts:
  channel: '#govuk-accounts'
  quotes:
    - We put users first. We strive to create services that bring real value to our users and that meet their needs and expectations.
    - We believe users should feel safe and confident when they use our services.
    - We design for everyone. We think about under-represented audiences from the start and check our biases throughout the design process.
    - We’re comfortable challenging assumptions and asking difficult questions. We speak truth to power.
    - We’re OK with change, failure, ambiguity, and adapting our approach.
    - We work collaboratively. Our work does not happen in discipline silos and we value the contributions of every discipline equally.
    - We treat each other with integrity, honesty and respect.
    - We work in the open so users and government colleagues know what we’re doing and why.
    - We know we can't do this alone. We need to work with teams across GDS and government to succeed.
    - We invest time and effort in increasing our understanding of the problems we’re working on. This will help us make things better for users and move the conversation about personalisation in government forward.

govuk-accounts-tech:
  channel: '#govuk-accounts-tech'
  exclude_titles:
    - DNM
    - DO NOT MERGE
    - DRAFT
    - PARKED
    - PROTOTYPE
    - WIP
  repos:
    - di-account-management-backend

govuk-datagovuk:
  channel: '#govuk-datagovuk'
  exclude_titles:
    - DNM
    - DO NOT MERGE
    - DRAFT
    - PARKED
    - PROTOTYPE
    - WIP
  repos:
    - ckan-functional-tests
    - ckan-mock-harvest-sources
    - ckanext-datagovuk
    - datagovuk-tech-docs
    - datagovuk_find
    - datagovuk_publish
    - datagovuk_publish_elasticsearch_monitor
    - datagovuk_reference

govuk-developers:
  channel: '#govuk-developers'
  exclude_titles:
    - DNM
    - DO NOT MERGE
    - DRAFT
    - PARKED
    - PROTOTYPE
    - WIP
  repos:
    - govuk-browser-extension
    - govuk-connect
    - govuk-developer-docs
    - govuk-docker
    - govuk-ithc-documentation
    - govuk-rfcs
    - govuk-rota-announcer
    - govuk-user-reviewer
    - slimmer

govuk-forms:
  channel: '#govuk-forms-tech'
  compact: true
  exclude_titles:
    - DNM
    - DO NOT MERGE
    - DRAFT
    - PARKED
    - PROTOTYPE
    - WIP
  repos:
    - forms
    - forms-admin
    - forms-api
    - forms-runner
    - forms-product-page

govuk-frontenders:
  channel: '#govuk-frontenders'
  exclude_titles:
    - DNM
    - DO NOT MERGE
    - DRAFT
    - PARKED
    - PROTOTYPE
    - WIP
  repos:
    - govuk_publishing_components
    - stylelint-config-gds

govuk-green-team:
  channel: '#govuk-green-team'
  quotes:
    - 'Remember to make time for personal development :big-brain:'
    - 'Remember to make time for community and corporate objectives :handshake:'
    - 'Remember to make time for wellbeing :happyseal:'
    - 'Remember to celebrating maintaining content :celebrate:'
    - "Remember to fill out the <https://docs.google.com/spreadsheets/d/1MV7ASHzDj_FWxix2tCo_EpuBmK0uvuYPnwjijjGIp00/edit#gid=0|spreadsheet> if you're going into the office soon so your teammates can look out for you. :office:"
    - 'Remember to add <https://docs.google.com/document/d/14L5FbIxpTEcjTXgA2deTAupr4y8n3JcIJixNSH5Czz0/edit|QOTDs> to the pinned list when you think of them'
    - 'Remember to <https://forms.gle/DdzRiptNuYQqA1Xn9|let me know> if there’s anything else I can help with or if you have any feedback. :mega:'

govuk-pay:
  channel: '#govuk-pay-tech'
  exclude_titles:
    - DO NOT MERGE
    - '[DRAFT]'
    - WIP
  repos:
    - gds-apple-developer-account-governance
    - pay-access-control
    - pay-adminusers
    - pay-api-docs-generator
    - pay-architecture
    - pay-aws-compliance
    - pay-cardid
    - pay-cardid-data
    - pay-ci
    - pay-cloudwatch-logs-s3-export
    - pay-cloudwatch-logs-s3-lambda
    - pay-code-analysis-config
    - pay-concourse
    - pay-concourse-deployment
    - pay-connector
    - pay-dockerfiles
    - pay-endtoend
    - pay-frontend
    - pay-infra
    - pay-java-commons
    - pay-js-commons
    - pay-ledger
    - pay-logging-lambdas
    - pay-nginx-forward-proxy
    - pay-nginx-proxy
    - pay-notifications
    - pay-performance-reporter
    - pay-perftests
    - pay-product-page
    - pay-products
    - pay-products-ui
    - pay-prototype
    - pay-publicapi
    - pay-publicauth
    - pay-scripts
    - pay-selfservice
    - pay-selfservice-policy-docs
    - pay-set-up-pre-commit
    - pay-smoke-tests
    - pay-stream-s3-sqs
    - pay-stubs
    - pay-team-manual
    - pay-tech-docs
    - pay-telegraf
    - pay-toolbox
    - pay-webhooks

govuk-platform-reliability:
  channel: '#govuk-platform-reliability-team'
  compact: true
  exclude_titles:
    - DNM
    - DO NOT MERGE
    - DRAFT
    - PARKED
    - PROTOTYPE
    - WIP
  quotes:
    - Be ready and willing to pair on work
    - Slack as primary point of contact; email for things you want to remember
    - Assume everyone is trying to do the right thing
    - Look out for each other
    - Make sure every meeting has a purpose and objective and explains who is required
    - Keep stand up updates as short as possible
    - Make sure anyone who wants to be involved in a decision has the opportunity to be
    - Try with each bit of work to upskill others
    - It's okay to spend some time understanding the thing(s) before implementing the solution
    - It's OK to pick up and work on something you don't understand yet
  repos:
    - bulk-merger
    - content-data-admin
    - content-data-api
    - gds_zendesk
    - govuk-app-deployment
    - govuk-aws
    - govuk-aws-data
    - govuk-cdn-config
    - govuk-dependencies
    - govuk-dependency-checker
    - govuk-deploy-lag-badger
    - govuk-dns
    - govuk-jenkinslib
    - govuk-lambda-app-deployment
    - govuk-load-testing
    - govuk-paas-office-ip-router
    - govuk-pact-broker
    - govuk-puppet
    - govuk-repo-mirror
    - govuk-saas-config
    - govuk-secondline-blinken
    - govuk-secrets
    - govuk-sentry-monitor
    - govuk-zendesk-display-screen
    - govuk_app_config
    - govuk_crawler_worker
    - govuk_seed_crawler
    - govuk_test
    - icinga_slack_webhook
    - locations-api
    - packager
    - plek
    - puppet-gor
    - rack-logstasher
    - release
    - rubocop-govuk
    - seal
    - smokey
    - support
    - support-api
    - upgrade-ruby-version

govuk-publishing-experience:
  channel: '#govuk-publishing-experience-tech'
  compact: true
  exclude_titles:
    - DNM
    - DO NOT MERGE
    - DRAFT
    - PARKED
    - PROTOTYPE
    - WIP
  repos:
    - collections-publisher
    - contacts-admin
    - content-publisher
    - content-tagger
    - govuk_admin_template
    - manuals-publisher
    - maslow
    - miller-columns-element
    - paste-html-to-govspeak
    - publisher
    - service-manual-publisher
    - short-url-manager
    - special-route-publisher
    - specialist-publisher
    - travel-advice-publisher
    - whitehall

govuk-publishing-platform:
  channel: '#govuk-publishing-platform'
  compact: true
  exclude_titles:
    - DNM
    - DO NOT MERGE
    - DRAFT
    - PARKED
    - PROTOTYPE
    - WIP
  repos:
    - asset-manager
    - content-store
    - gds-api-adapters
    - gds-sso
    - govspeak
    - govspeak-preview
    - govuk-content-api-docs
    - govuk-content-schemas
    - govuk_message_queue_consumer
    - govuk_schemas
    - govuk_sidekiq
    - hmrc-manuals-api
    - link-checker-api
    - optic14n
    - publishing-api
    - side-by-side-browser
    - sidekiq-monitoring
    - signon
    - transition
    - transition-config

govuk-replatforming:
  channel: '#govuk-replatforming'
  compact: true
  exclude_titles:
    - DNM
    - DO NOT MERGE
    - DRAFT
    - PARKED
    - PROTOTYPE
    - WIP
  repos:
    - govuk-helm-charts
    - govuk-infrastructure
    - govuk-kubernetes-cluster-user-docs
    - govuk-ruby-images

govwifi:
  channel: '#govwifi-monitoring'
  exclude_titles:
    - DO NOT MERGE
    - PROTOTYPE
    - WIP
    - PARKED
  repos:
    - govwifi-acceptance-tests
    - govwifi-admin
    - govwifi-authentication-api
    - govwifi-build
    - govwifi-builder-task
    - govwifi-concourse-deploy-pipeline
    - govwifi-concourse-runner
    - govwifi-dashboard
    - govwifi-database-backup
    - govwifi-dev-docs
    - govwifi-frontend
    - govwifi-logging-api
    - govwifi-product-page
    - govwifi-redirect
    - govwifi-safe-restarter
    - govwifi-shared-frontend
    - govwifi-smoke-tests
    - govwifi-tech-docs
    - govwifi-terraform
    - govwifi-user-signup-api
    - govwifi-watchdog

interaction-and-personalisation-govuk:
  channel: '#tech-interaction-and-personalisation'
  compact: true
  exclude_titles:
    - DNM
    - DO NOT MERGE
    - DRAFT
    - PARKED
    - PROTOTYPE
    - WIP

navigation-and-presentation-govuk:
  channel: '#navigation-and-presentation-govuk'
  compact: true
  repos:
    - authenticating-proxy
    - bouncer
    - cache-clearing-service
    - collections
    - frontend
    - government-frontend
    - info-frontend
    - router
    - router-api
    - service-manual-frontend
    - static
  exclude_titles:
    - DNM
    - DO NOT MERGE
    - DRAFT
    - PARKED
    - PROTOTYPE
    - WIP
  quotes:
    - Be Excellent To Each Other!
    - Don't be working if you're ill!
    - Is your work waiting to be reviewed? Make sure to ask someone.
    - Did you learn something cool recently? Share it with your fellow devs!

user-experience-measurement-govuk:
  channel: '#user-experience-measurement-govuk'
  compact: true
  exclude_titles:
    - DNM
    - DO NOT MERGE
    - DRAFT
    - PARKED
    - PROTOTYPE
    - WIP
